name: Build

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        default: ''

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    continue-on-error: true

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
        cache: false

    - name: Display Go version
      run: |
        go version

    - name: Get revision SHA and branch (safe)
      id: get-rev
      env:
        EVENT_NAME: ${{ github.event_name }}
        IS_MERGED: ${{ github.event.pull_request.merged }}
        GITHUB_SHA: ${{ github.sha }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
        REF_NAME: ${{ github.ref_name }}
      run: |
        if [ "$EVENT_NAME" == "pull_request" ]; then
          if [ "$IS_MERGED" == "true" ]; then
            sha="$GITHUB_SHA"
            branch="$PR_BASE_REF"
            echo "PR merged. SHA: ${sha}, Branch: ${branch}"
          else
            sha="$PR_HEAD_SHA"
            branch="$PR_HEAD_REF"
            echo "PR not yet merged. SHA: ${sha}, Branch: ${branch}"
          fi
        else
          sha="$GITHUB_SHA"
          branch="$REF_NAME"
          echo "$EVENT_NAME event. SHA: ${sha}, Branch: ${branch}"
        fi

        echo "sha=${sha}" >> "$GITHUB_OUTPUT"
        echo "branch=${branch}" >> "$GITHUB_OUTPUT"

    - name: Build urunc binaries
      id: build-urunc-binaries
      run: |
        make

    - name: Upload urunc_${{ matrix.arch }}
      uses: actions/upload-artifact@v4
      with:
        name: urunc_${{ matrix.arch }}-${{ github.run_id }}
        path: dist/urunc_static_${{ matrix.arch }}
    
    - name: Upload containerd-shim-urunc-v2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: containerd-shim-urunc-v2_${{ matrix.arch }}-${{ github.run_id }}
        path: dist/containerd-shim-urunc-v2_static_${{ matrix.arch }}
