name: Validate Files and Commit Messages

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        default: ''

jobs:
  linter-commitlint:
    name: Lint Commit Messages
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
      fail-fast: false
    continue-on-error: true
    defaults:
      run:
        working-directory: .github/linters


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm install --legacy-peer-deps

      - name: Run commitlint
        run: |
          git fetch origin main --depth=1
          npx commitlint --from=origin/main --config ./commitlint.config.js

  linter-typos:
    name: Spell Check Repo
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
      fail-fast: false
    continue-on-error: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Setup Node.js (for cspell)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
  
      - name: Install cspell
        run: npm install -g cspell
  
      - name: Spell check repo
        run: cspell --config .github/linters/.cspell.json
  

  linter-license-eye:
    name: Check License Headers
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
      fail-fast: false
    continue-on-error: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fix paths
        run: |
          echo "Unset GO PATH, as the following action conflicts with the already installed version"
          export GOPATH=
          echo "GOPATH=${GOPATH}" >> "$GITHUB_ENV"
          export GOTOOLDIR=
          echo "GOTOOLDIR=${GOTOOLDIR}" >> "$GITHUB_ENV"
          export GOROOT=
          echo "GOROOT=${GOROOT}" >> "$GITHUB_ENV"
        shell: bash

      - name: Run license-eye
        uses: apache/skywalking-eyes/header@main
        with:
          config: .github/linters/licenserc.yml
          token: ${{ secrets.GITHUB_TOKEN }}
